add missing error handling
scm-manager/scm-markdown-plantuml-plugin pull request #1
Opened 2021-01-17 08:31 UTC by Pilopa

## Proposed changes

The original implementation was missing proper error handling and display in the frontend. Because the `onerror` handler of the img html element doesnt provide the original exception, the image is now loaded through an xhr request and then transformed into a dataurl.

### Your checklist for this pull request

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] PR is well described and the description can be used as commit message on squash
- [ ] Related issues linked to PR if existing and labels set
- [ ] Target branch is not master (in most cases develop should bet the target of choice) 
- [ ] Code does not conflict with target branch
- [ ] New code is covered with unit tests
- [ ] CHANGELOG.md updated
- [ ] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md)
- [ ] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2021-01-17 08:32 UTC, Pilopa commented
Changelog doesnt need updating as the fix was prior to initial release

2021-01-19 08:43 UTC, sdorra requested changes

2021-01-19 08:43 UTC, sdorra commented on src/main/java/com/cloudogu/plantuml/PlantUmlResource.java
> +import java.lang.reflect.InvocationTargetException;
Unused import?

2021-01-19 08:43 UTC, sdorra commented on src/main/java/com/cloudogu/plantuml/PlantUMLRenderException.java
> +package com.cloudogu.plantuml;
Missing License Header

2021-01-19 08:43 UTC, sdorra commented on src/main/java/com/cloudogu/plantuml/PlantUmlResource.java
> +      throw new PlantUMLRenderException();
Please keep the root cause in the `PlantUMLRenderException`, so we can see the whole exception in the log.

2021-01-19 12:43 UTC, merged